### ISSUE TITLE
Makefile uses mercurial

### ISSUE THREAD

**Issue by codemedic** [ericpruitt/static-vim#1]
Now that this repo is hosted on github, the `mercurial` dependency can be dropped.
Otherwise it is one extra package to install in order to get the static vim compiled.

PS: @ericpruitt : Just the thing I was looking for my docker adventures recently; thanks.

**Comment by codemedic** [comment]
I have fixed it in my PR; please see #2

**Comment by ericpruitt** [comment]
Per my comment in the PR, this has been resolved by a rebased version of your commit (3f4d8e3).
